#!/usr/bin/env bash
# Displays all active IPv4 addresses on the machine.

IFCONFIG_OUTPUT=$(ifconfig)
IP_ADDRESSES=$(echo "$IFCONFIG_OUTPUT" | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | cut -b 11-)

echo "$IP_ADDRESSES"
