#!/usr/bin/env bash

# Define variables
KEY_NAME="school"
KEY_BITS=4096
PASSPHRASE="betty"

# Generate RSA key pair
ssh-keygen -f "./$KEY_NAME" -t rsa -b "$KEY_BITS" -N "$PASSPHRASE"

echo "RSA key pair created successfully."
